티스토리 오픈api 연결 작업
chanhong-jiwon-project/auto-commit-project pull request #7
Opened 2022-10-11 15:48 UTC by jiwon709

작업내용
---
티스토리 오픈api 를 이용하여 글 조회 response 호출 가능여부 확인   

작업기간
---
~10/16(일)

2022-10-12 09:30 UTC, chanhong-dev requested changes
yml 선언으로 변경 필요 #8

2022-10-16 05:59 UTC, jiwon709 commented
@chanhong-dev 님이 yml 으로 바꿨으니 해주세요.... 해줘... 해달라...

2022-10-16 11:14 UTC, chanhong-dev approved these changes

2022-10-19 09:35 UTC, jiwon709 commented
dev 머지하고 fix 브랜치 파서 수정 진행할게요

2022-10-19 09:35 UTC, merged